ARG GOLANG=buster
FROM golang:${GOLANG} as builder
# This is taken from https://gitlab.com/Tiemen/dgraph-aarch64
# If you just want to use the provided image from there, rather than building yourself just use the image registry.gitlab.com/tiemen/dgraph-aarch64

ENV CGO_ENABLED=0 GOOS=linux
RUN go get -u -v google.golang.org/grpc && \
    git clone --branch v1.2.2 https://www.github.com/dgraph-io/dgraph/ && \
    cd dgraph && \
    make install

RUN mkdir -p /dist/bin && \
    mkdir -p /dist/tmp && \
    mv ${GOPATH}/bin/dgraph /dist/bin/dgraph

FROM alpine:latest as dgraph
COPY --from=builder /dist /
ENV PATH=$PATH:/bin/
RUN chmod +x /bin/dgraph && apk --update --no-cache add bash

# Dgraph node type | gRPC-internal | gRPC-external | HTTP-external
#             zero |          5080 |             - |          6080
#            alpha |          7080 |          9080 |          8080
#            ratel |             - |             - |          8000
EXPOSE 5080 6080 7080 8080 8000 9080
CMD ["/bin/dgraph", "version"]