name: Publish Docker for API
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish API to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: jamesjarvis/whatsupkent/whatsupkent-api
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          dockerfile: Dockerfile-api
